// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               unknown
// source: dya/trackpad/trackpad.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "dya.trackpad";

export enum Sensitivity {
  SENSITIVITY_1X = 0,
  SENSITIVITY_2X = 1,
  SENSITIVITY_3X = 2,
  SENSITIVITY_4X = 3,
  UNRECOGNIZED = -1,
}

export interface TrackpadDevice {
  id: number;
  name: string;
  rotate90: boolean;
  xInvert: boolean;
  yInvert: boolean;
  sleep: boolean;
  noTaps: boolean;
  noSecondaryTap: boolean;
  absoluteGestures: boolean;
  tapToClick: boolean;
  doubleTapDrag: boolean;
  reverseCircularScroll: boolean;
  sensitivity: Sensitivity;
  xAxisZMin: number;
  yAxisZMin: number;
  touchZThreshold: number;
  xMax: number;
  yMax: number;
  edgeScrollMargin: number;
  pointerDivisor: number;
  tapTimeoutMs: number;
  doubleTapMs: number;
  tapMoveThreshold: number;
  scrollStep: number;
  ready: boolean;
}

export interface ListDevicesRequest {
}

export interface ListDevicesResponse {
  devices: TrackpadDevice[];
}

export interface GetDeviceRequest {
  id: number;
}

export interface GetDeviceResponse {
  device: TrackpadDevice | undefined;
}

export interface SetSleepRequest {
  id: number;
  enabled: boolean;
}

export interface SetSleepResponse {
}

export interface ResetDeviceRequest {
  id: number;
}

export interface ResetDeviceResponse {
}

export interface ErrorResponse {
  message: string;
}

export interface Request {
  listDevices?: ListDevicesRequest | undefined;
  getDevice?: GetDeviceRequest | undefined;
  setSleep?: SetSleepRequest | undefined;
  resetDevice?: ResetDeviceRequest | undefined;
}

export interface Response {
  error?: ErrorResponse | undefined;
  listDevices?: ListDevicesResponse | undefined;
  getDevice?: GetDeviceResponse | undefined;
  setSleep?: SetSleepResponse | undefined;
  resetDevice?: ResetDeviceResponse | undefined;
}

function createBaseTrackpadDevice(): TrackpadDevice {
  return {
    id: 0,
    name: "",
    rotate90: false,
    xInvert: false,
    yInvert: false,
    sleep: false,
    noTaps: false,
    noSecondaryTap: false,
    absoluteGestures: false,
    tapToClick: false,
    doubleTapDrag: false,
    reverseCircularScroll: false,
    sensitivity: 0,
    xAxisZMin: 0,
    yAxisZMin: 0,
    touchZThreshold: 0,
    xMax: 0,
    yMax: 0,
    edgeScrollMargin: 0,
    pointerDivisor: 0,
    tapTimeoutMs: 0,
    doubleTapMs: 0,
    tapMoveThreshold: 0,
    scrollStep: 0,
    ready: false,
  };
}

export const TrackpadDevice: MessageFns<TrackpadDevice> = {
  encode(message: TrackpadDevice, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.rotate90 !== false) {
      writer.uint32(24).bool(message.rotate90);
    }
    if (message.xInvert !== false) {
      writer.uint32(32).bool(message.xInvert);
    }
    if (message.yInvert !== false) {
      writer.uint32(40).bool(message.yInvert);
    }
    if (message.sleep !== false) {
      writer.uint32(48).bool(message.sleep);
    }
    if (message.noTaps !== false) {
      writer.uint32(56).bool(message.noTaps);
    }
    if (message.noSecondaryTap !== false) {
      writer.uint32(64).bool(message.noSecondaryTap);
    }
    if (message.absoluteGestures !== false) {
      writer.uint32(72).bool(message.absoluteGestures);
    }
    if (message.tapToClick !== false) {
      writer.uint32(80).bool(message.tapToClick);
    }
    if (message.doubleTapDrag !== false) {
      writer.uint32(88).bool(message.doubleTapDrag);
    }
    if (message.reverseCircularScroll !== false) {
      writer.uint32(96).bool(message.reverseCircularScroll);
    }
    if (message.sensitivity !== 0) {
      writer.uint32(104).int32(message.sensitivity);
    }
    if (message.xAxisZMin !== 0) {
      writer.uint32(112).uint32(message.xAxisZMin);
    }
    if (message.yAxisZMin !== 0) {
      writer.uint32(120).uint32(message.yAxisZMin);
    }
    if (message.touchZThreshold !== 0) {
      writer.uint32(128).uint32(message.touchZThreshold);
    }
    if (message.xMax !== 0) {
      writer.uint32(136).uint32(message.xMax);
    }
    if (message.yMax !== 0) {
      writer.uint32(144).uint32(message.yMax);
    }
    if (message.edgeScrollMargin !== 0) {
      writer.uint32(152).uint32(message.edgeScrollMargin);
    }
    if (message.pointerDivisor !== 0) {
      writer.uint32(160).uint32(message.pointerDivisor);
    }
    if (message.tapTimeoutMs !== 0) {
      writer.uint32(168).uint32(message.tapTimeoutMs);
    }
    if (message.doubleTapMs !== 0) {
      writer.uint32(176).uint32(message.doubleTapMs);
    }
    if (message.tapMoveThreshold !== 0) {
      writer.uint32(184).uint32(message.tapMoveThreshold);
    }
    if (message.scrollStep !== 0) {
      writer.uint32(192).uint32(message.scrollStep);
    }
    if (message.ready !== false) {
      writer.uint32(200).bool(message.ready);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TrackpadDevice {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrackpadDevice();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.rotate90 = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.xInvert = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.yInvert = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.sleep = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.noTaps = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.noSecondaryTap = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.absoluteGestures = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.tapToClick = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.doubleTapDrag = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.reverseCircularScroll = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.sensitivity = reader.int32() as any;
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.xAxisZMin = reader.uint32();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.yAxisZMin = reader.uint32();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.touchZThreshold = reader.uint32();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.xMax = reader.uint32();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.yMax = reader.uint32();
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.edgeScrollMargin = reader.uint32();
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.pointerDivisor = reader.uint32();
          continue;
        }
        case 21: {
          if (tag !== 168) {
            break;
          }

          message.tapTimeoutMs = reader.uint32();
          continue;
        }
        case 22: {
          if (tag !== 176) {
            break;
          }

          message.doubleTapMs = reader.uint32();
          continue;
        }
        case 23: {
          if (tag !== 184) {
            break;
          }

          message.tapMoveThreshold = reader.uint32();
          continue;
        }
        case 24: {
          if (tag !== 192) {
            break;
          }

          message.scrollStep = reader.uint32();
          continue;
        }
        case 25: {
          if (tag !== 200) {
            break;
          }

          message.ready = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<TrackpadDevice>): TrackpadDevice {
    return TrackpadDevice.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TrackpadDevice>): TrackpadDevice {
    const message = createBaseTrackpadDevice();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.rotate90 = object.rotate90 ?? false;
    message.xInvert = object.xInvert ?? false;
    message.yInvert = object.yInvert ?? false;
    message.sleep = object.sleep ?? false;
    message.noTaps = object.noTaps ?? false;
    message.noSecondaryTap = object.noSecondaryTap ?? false;
    message.absoluteGestures = object.absoluteGestures ?? false;
    message.tapToClick = object.tapToClick ?? false;
    message.doubleTapDrag = object.doubleTapDrag ?? false;
    message.reverseCircularScroll = object.reverseCircularScroll ?? false;
    message.sensitivity = object.sensitivity ?? 0;
    message.xAxisZMin = object.xAxisZMin ?? 0;
    message.yAxisZMin = object.yAxisZMin ?? 0;
    message.touchZThreshold = object.touchZThreshold ?? 0;
    message.xMax = object.xMax ?? 0;
    message.yMax = object.yMax ?? 0;
    message.edgeScrollMargin = object.edgeScrollMargin ?? 0;
    message.pointerDivisor = object.pointerDivisor ?? 0;
    message.tapTimeoutMs = object.tapTimeoutMs ?? 0;
    message.doubleTapMs = object.doubleTapMs ?? 0;
    message.tapMoveThreshold = object.tapMoveThreshold ?? 0;
    message.scrollStep = object.scrollStep ?? 0;
    message.ready = object.ready ?? false;
    return message;
  },
};

function createBaseListDevicesRequest(): ListDevicesRequest {
  return {};
}

export const ListDevicesRequest: MessageFns<ListDevicesRequest> = {
  encode(_: ListDevicesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListDevicesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListDevicesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListDevicesRequest>): ListDevicesRequest {
    return ListDevicesRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ListDevicesRequest>): ListDevicesRequest {
    const message = createBaseListDevicesRequest();
    return message;
  },
};

function createBaseListDevicesResponse(): ListDevicesResponse {
  return { devices: [] };
}

export const ListDevicesResponse: MessageFns<ListDevicesResponse> = {
  encode(message: ListDevicesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.devices) {
      TrackpadDevice.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListDevicesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListDevicesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.devices.push(TrackpadDevice.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListDevicesResponse>): ListDevicesResponse {
    return ListDevicesResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListDevicesResponse>): ListDevicesResponse {
    const message = createBaseListDevicesResponse();
    message.devices = object.devices?.map((e) => TrackpadDevice.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetDeviceRequest(): GetDeviceRequest {
  return { id: 0 };
}

export const GetDeviceRequest: MessageFns<GetDeviceRequest> = {
  encode(message: GetDeviceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetDeviceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDeviceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetDeviceRequest>): GetDeviceRequest {
    return GetDeviceRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetDeviceRequest>): GetDeviceRequest {
    const message = createBaseGetDeviceRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseGetDeviceResponse(): GetDeviceResponse {
  return { device: undefined };
}

export const GetDeviceResponse: MessageFns<GetDeviceResponse> = {
  encode(message: GetDeviceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.device !== undefined) {
      TrackpadDevice.encode(message.device, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetDeviceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDeviceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.device = TrackpadDevice.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetDeviceResponse>): GetDeviceResponse {
    return GetDeviceResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetDeviceResponse>): GetDeviceResponse {
    const message = createBaseGetDeviceResponse();
    message.device = (object.device !== undefined && object.device !== null)
      ? TrackpadDevice.fromPartial(object.device)
      : undefined;
    return message;
  },
};

function createBaseSetSleepRequest(): SetSleepRequest {
  return { id: 0, enabled: false };
}

export const SetSleepRequest: MessageFns<SetSleepRequest> = {
  encode(message: SetSleepRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.enabled !== false) {
      writer.uint32(16).bool(message.enabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetSleepRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetSleepRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetSleepRequest>): SetSleepRequest {
    return SetSleepRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetSleepRequest>): SetSleepRequest {
    const message = createBaseSetSleepRequest();
    message.id = object.id ?? 0;
    message.enabled = object.enabled ?? false;
    return message;
  },
};

function createBaseSetSleepResponse(): SetSleepResponse {
  return {};
}

export const SetSleepResponse: MessageFns<SetSleepResponse> = {
  encode(_: SetSleepResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetSleepResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetSleepResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetSleepResponse>): SetSleepResponse {
    return SetSleepResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<SetSleepResponse>): SetSleepResponse {
    const message = createBaseSetSleepResponse();
    return message;
  },
};

function createBaseResetDeviceRequest(): ResetDeviceRequest {
  return { id: 0 };
}

export const ResetDeviceRequest: MessageFns<ResetDeviceRequest> = {
  encode(message: ResetDeviceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetDeviceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetDeviceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ResetDeviceRequest>): ResetDeviceRequest {
    return ResetDeviceRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ResetDeviceRequest>): ResetDeviceRequest {
    const message = createBaseResetDeviceRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseResetDeviceResponse(): ResetDeviceResponse {
  return {};
}

export const ResetDeviceResponse: MessageFns<ResetDeviceResponse> = {
  encode(_: ResetDeviceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetDeviceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetDeviceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ResetDeviceResponse>): ResetDeviceResponse {
    return ResetDeviceResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ResetDeviceResponse>): ResetDeviceResponse {
    const message = createBaseResetDeviceResponse();
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseRequest(): Request {
  return { listDevices: undefined, getDevice: undefined, setSleep: undefined, resetDevice: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.listDevices !== undefined) {
      ListDevicesRequest.encode(message.listDevices, writer.uint32(10).fork()).join();
    }
    if (message.getDevice !== undefined) {
      GetDeviceRequest.encode(message.getDevice, writer.uint32(18).fork()).join();
    }
    if (message.setSleep !== undefined) {
      SetSleepRequest.encode(message.setSleep, writer.uint32(26).fork()).join();
    }
    if (message.resetDevice !== undefined) {
      ResetDeviceRequest.encode(message.resetDevice, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.listDevices = ListDevicesRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.getDevice = GetDeviceRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.setSleep = SetSleepRequest.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.resetDevice = ResetDeviceRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.listDevices = (object.listDevices !== undefined && object.listDevices !== null)
      ? ListDevicesRequest.fromPartial(object.listDevices)
      : undefined;
    message.getDevice = (object.getDevice !== undefined && object.getDevice !== null)
      ? GetDeviceRequest.fromPartial(object.getDevice)
      : undefined;
    message.setSleep = (object.setSleep !== undefined && object.setSleep !== null)
      ? SetSleepRequest.fromPartial(object.setSleep)
      : undefined;
    message.resetDevice = (object.resetDevice !== undefined && object.resetDevice !== null)
      ? ResetDeviceRequest.fromPartial(object.resetDevice)
      : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return {
    error: undefined,
    listDevices: undefined,
    getDevice: undefined,
    setSleep: undefined,
    resetDevice: undefined,
  };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.listDevices !== undefined) {
      ListDevicesResponse.encode(message.listDevices, writer.uint32(18).fork()).join();
    }
    if (message.getDevice !== undefined) {
      GetDeviceResponse.encode(message.getDevice, writer.uint32(26).fork()).join();
    }
    if (message.setSleep !== undefined) {
      SetSleepResponse.encode(message.setSleep, writer.uint32(34).fork()).join();
    }
    if (message.resetDevice !== undefined) {
      ResetDeviceResponse.encode(message.resetDevice, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.listDevices = ListDevicesResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.getDevice = GetDeviceResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.setSleep = SetSleepResponse.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.resetDevice = ResetDeviceResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.listDevices = (object.listDevices !== undefined && object.listDevices !== null)
      ? ListDevicesResponse.fromPartial(object.listDevices)
      : undefined;
    message.getDevice = (object.getDevice !== undefined && object.getDevice !== null)
      ? GetDeviceResponse.fromPartial(object.getDevice)
      : undefined;
    message.setSleep = (object.setSleep !== undefined && object.setSleep !== null)
      ? SetSleepResponse.fromPartial(object.setSleep)
      : undefined;
    message.resetDevice = (object.resetDevice !== undefined && object.resetDevice !== null)
      ? ResetDeviceResponse.fromPartial(object.resetDevice)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
