/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "trackpad.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(dya_trackpad_TrackpadDevice, dya_trackpad_TrackpadDevice, AUTO)


PB_BIND(dya_trackpad_ListDevicesRequest, dya_trackpad_ListDevicesRequest, AUTO)


PB_BIND(dya_trackpad_ListDevicesResponse, dya_trackpad_ListDevicesResponse, AUTO)


PB_BIND(dya_trackpad_GetDeviceRequest, dya_trackpad_GetDeviceRequest, AUTO)


PB_BIND(dya_trackpad_GetDeviceResponse, dya_trackpad_GetDeviceResponse, AUTO)


PB_BIND(dya_trackpad_SetSleepRequest, dya_trackpad_SetSleepRequest, AUTO)


PB_BIND(dya_trackpad_SetSleepResponse, dya_trackpad_SetSleepResponse, AUTO)


PB_BIND(dya_trackpad_ResetDeviceRequest, dya_trackpad_ResetDeviceRequest, AUTO)


PB_BIND(dya_trackpad_ResetDeviceResponse, dya_trackpad_ResetDeviceResponse, AUTO)


PB_BIND(dya_trackpad_ErrorResponse, dya_trackpad_ErrorResponse, AUTO)


PB_BIND(dya_trackpad_Request, dya_trackpad_Request, AUTO)


PB_BIND(dya_trackpad_Response, dya_trackpad_Response, AUTO)




