/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_DYA_TRACKPAD_TRACKPAD_PB_H_INCLUDED
#define PB_DYA_TRACKPAD_TRACKPAD_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _dya_trackpad_Sensitivity {
    dya_trackpad_Sensitivity_SENSITIVITY_1X = 0,
    dya_trackpad_Sensitivity_SENSITIVITY_2X = 1,
    dya_trackpad_Sensitivity_SENSITIVITY_3X = 2,
    dya_trackpad_Sensitivity_SENSITIVITY_4X = 3
} dya_trackpad_Sensitivity;

/* Struct definitions */
typedef struct _dya_trackpad_TrackpadDevice {
    uint32_t id;
    char name[48];
    bool rotate90;
    bool xInvert;
    bool yInvert;
    bool sleep;
    bool noTaps;
    bool noSecondaryTap;
    bool absoluteGestures;
    bool tapToClick;
    bool doubleTapDrag;
    bool reverseCircularScroll;
    dya_trackpad_Sensitivity sensitivity;
    uint32_t xAxisZMin;
    uint32_t yAxisZMin;
    uint32_t touchZThreshold;
    uint32_t xMax;
    uint32_t yMax;
    uint32_t edgeScrollMargin;
    uint32_t pointerDivisor;
    uint32_t tapTimeoutMs;
    uint32_t doubleTapMs;
    uint32_t tapMoveThreshold;
    uint32_t scrollStep;
    bool ready;
} dya_trackpad_TrackpadDevice;

typedef struct _dya_trackpad_ListDevicesRequest {
    char dummy_field;
} dya_trackpad_ListDevicesRequest;

typedef struct _dya_trackpad_ListDevicesResponse {
    pb_callback_t devices;
} dya_trackpad_ListDevicesResponse;

typedef struct _dya_trackpad_GetDeviceRequest {
    uint32_t id;
} dya_trackpad_GetDeviceRequest;

typedef struct _dya_trackpad_GetDeviceResponse {
    bool has_device;
    dya_trackpad_TrackpadDevice device;
} dya_trackpad_GetDeviceResponse;

typedef struct _dya_trackpad_SetSleepRequest {
    uint32_t id;
    bool enabled;
} dya_trackpad_SetSleepRequest;

typedef struct _dya_trackpad_SetSleepResponse {
    char dummy_field;
} dya_trackpad_SetSleepResponse;

typedef struct _dya_trackpad_ResetDeviceRequest {
    uint32_t id;
} dya_trackpad_ResetDeviceRequest;

typedef struct _dya_trackpad_ResetDeviceResponse {
    char dummy_field;
} dya_trackpad_ResetDeviceResponse;

typedef struct _dya_trackpad_SetDeviceRequest {
    bool has_device;
    dya_trackpad_TrackpadDevice device;
} dya_trackpad_SetDeviceRequest;

typedef struct _dya_trackpad_ErrorResponse {
    char message[96];
} dya_trackpad_ErrorResponse;

typedef struct _dya_trackpad_Request {
    pb_size_t which_request_type;
    union {
        dya_trackpad_ListDevicesRequest list_devices;
        dya_trackpad_GetDeviceRequest get_device;
        dya_trackpad_SetSleepRequest set_sleep;
        dya_trackpad_ResetDeviceRequest reset_device;
        dya_trackpad_SetDeviceRequest set_device;
    } request_type;
} dya_trackpad_Request;

typedef struct _dya_trackpad_Response {
    pb_size_t which_response_type;
    union {
        dya_trackpad_ErrorResponse error;
        dya_trackpad_ListDevicesResponse list_devices;
        dya_trackpad_GetDeviceResponse get_device;
        dya_trackpad_SetSleepResponse set_sleep;
        dya_trackpad_ResetDeviceResponse reset_device;
    } response_type;
} dya_trackpad_Response;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _dya_trackpad_Sensitivity_MIN dya_trackpad_Sensitivity_SENSITIVITY_1X
#define _dya_trackpad_Sensitivity_MAX dya_trackpad_Sensitivity_SENSITIVITY_4X
#define _dya_trackpad_Sensitivity_ARRAYSIZE ((dya_trackpad_Sensitivity)(dya_trackpad_Sensitivity_SENSITIVITY_4X+1))

#define dya_trackpad_TrackpadDevice_sensitivity_ENUMTYPE dya_trackpad_Sensitivity













/* Initializer values for message structs */
#define dya_trackpad_TrackpadDevice_init_default {0, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, _dya_trackpad_Sensitivity_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define dya_trackpad_ListDevicesRequest_init_default {0}
#define dya_trackpad_ListDevicesResponse_init_default {{{NULL}, NULL}}
#define dya_trackpad_GetDeviceRequest_init_default {0}
#define dya_trackpad_GetDeviceResponse_init_default {false, dya_trackpad_TrackpadDevice_init_default}
#define dya_trackpad_SetSleepRequest_init_default {0, 0}
#define dya_trackpad_SetSleepResponse_init_default {0}
#define dya_trackpad_ResetDeviceRequest_init_default {0}
#define dya_trackpad_ResetDeviceResponse_init_default {0}
#define dya_trackpad_SetDeviceRequest_init_default {false, dya_trackpad_TrackpadDevice_init_default}
#define dya_trackpad_ErrorResponse_init_default  {""}
#define dya_trackpad_Request_init_default        {0, {dya_trackpad_ListDevicesRequest_init_default}}
#define dya_trackpad_Response_init_default       {0, {dya_trackpad_ErrorResponse_init_default}}
#define dya_trackpad_TrackpadDevice_init_zero    {0, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, _dya_trackpad_Sensitivity_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define dya_trackpad_ListDevicesRequest_init_zero {0}
#define dya_trackpad_ListDevicesResponse_init_zero {{{NULL}, NULL}}
#define dya_trackpad_GetDeviceRequest_init_zero  {0}
#define dya_trackpad_GetDeviceResponse_init_zero {false, dya_trackpad_TrackpadDevice_init_zero}
#define dya_trackpad_SetSleepRequest_init_zero   {0, 0}
#define dya_trackpad_SetSleepResponse_init_zero  {0}
#define dya_trackpad_ResetDeviceRequest_init_zero {0}
#define dya_trackpad_ResetDeviceResponse_init_zero {0}
#define dya_trackpad_SetDeviceRequest_init_zero  {false, dya_trackpad_TrackpadDevice_init_zero}
#define dya_trackpad_ErrorResponse_init_zero     {""}
#define dya_trackpad_Request_init_zero           {0, {dya_trackpad_ListDevicesRequest_init_zero}}
#define dya_trackpad_Response_init_zero          {0, {dya_trackpad_ErrorResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define dya_trackpad_TrackpadDevice_id_tag       1
#define dya_trackpad_TrackpadDevice_name_tag     2
#define dya_trackpad_TrackpadDevice_rotate90_tag 3
#define dya_trackpad_TrackpadDevice_xInvert_tag  4
#define dya_trackpad_TrackpadDevice_yInvert_tag  5
#define dya_trackpad_TrackpadDevice_sleep_tag    6
#define dya_trackpad_TrackpadDevice_noTaps_tag   7
#define dya_trackpad_TrackpadDevice_noSecondaryTap_tag 8
#define dya_trackpad_TrackpadDevice_absoluteGestures_tag 9
#define dya_trackpad_TrackpadDevice_tapToClick_tag 10
#define dya_trackpad_TrackpadDevice_doubleTapDrag_tag 11
#define dya_trackpad_TrackpadDevice_reverseCircularScroll_tag 12
#define dya_trackpad_TrackpadDevice_sensitivity_tag 13
#define dya_trackpad_TrackpadDevice_xAxisZMin_tag 14
#define dya_trackpad_TrackpadDevice_yAxisZMin_tag 15
#define dya_trackpad_TrackpadDevice_touchZThreshold_tag 16
#define dya_trackpad_TrackpadDevice_xMax_tag     17
#define dya_trackpad_TrackpadDevice_yMax_tag     18
#define dya_trackpad_TrackpadDevice_edgeScrollMargin_tag 19
#define dya_trackpad_TrackpadDevice_pointerDivisor_tag 20
#define dya_trackpad_TrackpadDevice_tapTimeoutMs_tag 21
#define dya_trackpad_TrackpadDevice_doubleTapMs_tag 22
#define dya_trackpad_TrackpadDevice_tapMoveThreshold_tag 23
#define dya_trackpad_TrackpadDevice_scrollStep_tag 24
#define dya_trackpad_TrackpadDevice_ready_tag    25
#define dya_trackpad_ListDevicesResponse_devices_tag 1
#define dya_trackpad_GetDeviceRequest_id_tag     1
#define dya_trackpad_GetDeviceResponse_device_tag 1
#define dya_trackpad_SetSleepRequest_id_tag      1
#define dya_trackpad_SetSleepRequest_enabled_tag 2
#define dya_trackpad_ResetDeviceRequest_id_tag   1
#define dya_trackpad_SetDeviceRequest_device_tag 1
#define dya_trackpad_ErrorResponse_message_tag   1
#define dya_trackpad_Request_list_devices_tag    1
#define dya_trackpad_Request_get_device_tag      2
#define dya_trackpad_Request_set_sleep_tag       3
#define dya_trackpad_Request_reset_device_tag    4
#define dya_trackpad_Request_set_device_tag      5
#define dya_trackpad_Response_error_tag          1
#define dya_trackpad_Response_list_devices_tag   2
#define dya_trackpad_Response_get_device_tag     3
#define dya_trackpad_Response_set_sleep_tag      4
#define dya_trackpad_Response_reset_device_tag   5

/* Struct field encoding specification for nanopb */
#define dya_trackpad_TrackpadDevice_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, BOOL,     rotate90,          3) \
X(a, STATIC,   SINGULAR, BOOL,     xInvert,           4) \
X(a, STATIC,   SINGULAR, BOOL,     yInvert,           5) \
X(a, STATIC,   SINGULAR, BOOL,     sleep,             6) \
X(a, STATIC,   SINGULAR, BOOL,     noTaps,            7) \
X(a, STATIC,   SINGULAR, BOOL,     noSecondaryTap,    8) \
X(a, STATIC,   SINGULAR, BOOL,     absoluteGestures,   9) \
X(a, STATIC,   SINGULAR, BOOL,     tapToClick,       10) \
X(a, STATIC,   SINGULAR, BOOL,     doubleTapDrag,    11) \
X(a, STATIC,   SINGULAR, BOOL,     reverseCircularScroll,  12) \
X(a, STATIC,   SINGULAR, UENUM,    sensitivity,      13) \
X(a, STATIC,   SINGULAR, UINT32,   xAxisZMin,        14) \
X(a, STATIC,   SINGULAR, UINT32,   yAxisZMin,        15) \
X(a, STATIC,   SINGULAR, UINT32,   touchZThreshold,  16) \
X(a, STATIC,   SINGULAR, UINT32,   xMax,             17) \
X(a, STATIC,   SINGULAR, UINT32,   yMax,             18) \
X(a, STATIC,   SINGULAR, UINT32,   edgeScrollMargin,  19) \
X(a, STATIC,   SINGULAR, UINT32,   pointerDivisor,   20) \
X(a, STATIC,   SINGULAR, UINT32,   tapTimeoutMs,     21) \
X(a, STATIC,   SINGULAR, UINT32,   doubleTapMs,      22) \
X(a, STATIC,   SINGULAR, UINT32,   tapMoveThreshold,  23) \
X(a, STATIC,   SINGULAR, UINT32,   scrollStep,       24) \
X(a, STATIC,   SINGULAR, BOOL,     ready,            25)
#define dya_trackpad_TrackpadDevice_CALLBACK NULL
#define dya_trackpad_TrackpadDevice_DEFAULT NULL

#define dya_trackpad_ListDevicesRequest_FIELDLIST(X, a) \

#define dya_trackpad_ListDevicesRequest_CALLBACK NULL
#define dya_trackpad_ListDevicesRequest_DEFAULT NULL

#define dya_trackpad_ListDevicesResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  devices,           1)
#define dya_trackpad_ListDevicesResponse_CALLBACK pb_default_field_callback
#define dya_trackpad_ListDevicesResponse_DEFAULT NULL
#define dya_trackpad_ListDevicesResponse_devices_MSGTYPE dya_trackpad_TrackpadDevice

#define dya_trackpad_GetDeviceRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1)
#define dya_trackpad_GetDeviceRequest_CALLBACK NULL
#define dya_trackpad_GetDeviceRequest_DEFAULT NULL

#define dya_trackpad_GetDeviceResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device,            1)
#define dya_trackpad_GetDeviceResponse_CALLBACK NULL
#define dya_trackpad_GetDeviceResponse_DEFAULT NULL
#define dya_trackpad_GetDeviceResponse_device_MSGTYPE dya_trackpad_TrackpadDevice

#define dya_trackpad_SetSleepRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           2)
#define dya_trackpad_SetSleepRequest_CALLBACK NULL
#define dya_trackpad_SetSleepRequest_DEFAULT NULL

#define dya_trackpad_SetSleepResponse_FIELDLIST(X, a) \

#define dya_trackpad_SetSleepResponse_CALLBACK NULL
#define dya_trackpad_SetSleepResponse_DEFAULT NULL

#define dya_trackpad_ResetDeviceRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1)
#define dya_trackpad_ResetDeviceRequest_CALLBACK NULL
#define dya_trackpad_ResetDeviceRequest_DEFAULT NULL

#define dya_trackpad_ResetDeviceResponse_FIELDLIST(X, a) \

#define dya_trackpad_ResetDeviceResponse_CALLBACK NULL
#define dya_trackpad_ResetDeviceResponse_DEFAULT NULL

#define dya_trackpad_SetDeviceRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device,            1)
#define dya_trackpad_SetDeviceRequest_CALLBACK NULL
#define dya_trackpad_SetDeviceRequest_DEFAULT NULL
#define dya_trackpad_SetDeviceRequest_device_MSGTYPE dya_trackpad_TrackpadDevice

#define dya_trackpad_ErrorResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message,           1)
#define dya_trackpad_ErrorResponse_CALLBACK NULL
#define dya_trackpad_ErrorResponse_DEFAULT NULL

#define dya_trackpad_Request_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,list_devices,request_type.list_devices),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,get_device,request_type.get_device),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,set_sleep,request_type.set_sleep),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,reset_device,request_type.reset_device),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,set_device,request_type.set_device),   5)
#define dya_trackpad_Request_CALLBACK NULL
#define dya_trackpad_Request_DEFAULT NULL
#define dya_trackpad_Request_request_type_list_devices_MSGTYPE dya_trackpad_ListDevicesRequest
#define dya_trackpad_Request_request_type_get_device_MSGTYPE dya_trackpad_GetDeviceRequest
#define dya_trackpad_Request_request_type_set_sleep_MSGTYPE dya_trackpad_SetSleepRequest
#define dya_trackpad_Request_request_type_reset_device_MSGTYPE dya_trackpad_ResetDeviceRequest
#define dya_trackpad_Request_request_type_set_device_MSGTYPE dya_trackpad_SetDeviceRequest

#define dya_trackpad_Response_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,error,response_type.error),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,list_devices,response_type.list_devices),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,get_device,response_type.get_device),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,set_sleep,response_type.set_sleep),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,reset_device,response_type.reset_device),   5)
#define dya_trackpad_Response_CALLBACK NULL
#define dya_trackpad_Response_DEFAULT NULL
#define dya_trackpad_Response_response_type_error_MSGTYPE dya_trackpad_ErrorResponse
#define dya_trackpad_Response_response_type_list_devices_MSGTYPE dya_trackpad_ListDevicesResponse
#define dya_trackpad_Response_response_type_get_device_MSGTYPE dya_trackpad_GetDeviceResponse
#define dya_trackpad_Response_response_type_set_sleep_MSGTYPE dya_trackpad_SetSleepResponse
#define dya_trackpad_Response_response_type_reset_device_MSGTYPE dya_trackpad_ResetDeviceResponse

extern const pb_msgdesc_t dya_trackpad_TrackpadDevice_msg;
extern const pb_msgdesc_t dya_trackpad_ListDevicesRequest_msg;
extern const pb_msgdesc_t dya_trackpad_ListDevicesResponse_msg;
extern const pb_msgdesc_t dya_trackpad_GetDeviceRequest_msg;
extern const pb_msgdesc_t dya_trackpad_GetDeviceResponse_msg;
extern const pb_msgdesc_t dya_trackpad_SetSleepRequest_msg;
extern const pb_msgdesc_t dya_trackpad_SetSleepResponse_msg;
extern const pb_msgdesc_t dya_trackpad_ResetDeviceRequest_msg;
extern const pb_msgdesc_t dya_trackpad_ResetDeviceResponse_msg;
extern const pb_msgdesc_t dya_trackpad_SetDeviceRequest_msg;
extern const pb_msgdesc_t dya_trackpad_ErrorResponse_msg;
extern const pb_msgdesc_t dya_trackpad_Request_msg;
extern const pb_msgdesc_t dya_trackpad_Response_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define dya_trackpad_TrackpadDevice_fields &dya_trackpad_TrackpadDevice_msg
#define dya_trackpad_ListDevicesRequest_fields &dya_trackpad_ListDevicesRequest_msg
#define dya_trackpad_ListDevicesResponse_fields &dya_trackpad_ListDevicesResponse_msg
#define dya_trackpad_GetDeviceRequest_fields &dya_trackpad_GetDeviceRequest_msg
#define dya_trackpad_GetDeviceResponse_fields &dya_trackpad_GetDeviceResponse_msg
#define dya_trackpad_SetSleepRequest_fields &dya_trackpad_SetSleepRequest_msg
#define dya_trackpad_SetSleepResponse_fields &dya_trackpad_SetSleepResponse_msg
#define dya_trackpad_ResetDeviceRequest_fields &dya_trackpad_ResetDeviceRequest_msg
#define dya_trackpad_ResetDeviceResponse_fields &dya_trackpad_ResetDeviceResponse_msg
#define dya_trackpad_SetDeviceRequest_fields &dya_trackpad_SetDeviceRequest_msg
#define dya_trackpad_ErrorResponse_fields &dya_trackpad_ErrorResponse_msg
#define dya_trackpad_Request_fields &dya_trackpad_Request_msg
#define dya_trackpad_Response_fields &dya_trackpad_Response_msg

/* Maximum encoded size of messages (where known) */
/* dya_trackpad_ListDevicesResponse_size depends on runtime parameters */
/* dya_trackpad_Response_size depends on runtime parameters */
#define DYA_TRACKPAD_TRACKPAD_PB_H_MAX_SIZE      dya_trackpad_GetDeviceResponse_size
#define dya_trackpad_ErrorResponse_size          97
#define dya_trackpad_GetDeviceRequest_size       6
#define dya_trackpad_GetDeviceResponse_size      158
#define dya_trackpad_ListDevicesRequest_size     0
#define dya_trackpad_Request_size                10
#define dya_trackpad_ResetDeviceRequest_size     6
#define dya_trackpad_ResetDeviceResponse_size    0
#define dya_trackpad_SetSleepRequest_size        8
#define dya_trackpad_SetSleepResponse_size       0
#define dya_trackpad_TrackpadDevice_size         155

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
